### ISSUE TITLE
更换etcdv3 客户端实现

### ISSUE THREAD

**Issue by hsz1273327** [liyue201/grpc-lb#11]
CoreOS上的etcd3客户端实现看项目描述已经过期....说让用官方库

**Comment by liyue201** [comment]
etcd的老的客户端版本依赖很混乱，后续升级到3.4.7就好了，但目前无法升级。可以参考这个
https://colobu.com/2020/04/09/accidents-of-etcd-and-go-module/

**Comment by hsz1273327** [comment]
好的.辛苦~
