### ISSUE TITLE
错误的ticker时间

### ISSUE THREAD

**Issue by GoneGo1ng** [liyue201/grpc-lb#12]
registry/etcd3/registrar.go第95行的ticker的时间，经过NewRegistrar赋值时的`/ time.Second`操作后，已经变成ms了，导致下面这个ticker的间隔时间成了2ms（我不确定你是不是想要2ms这个效果，应该不需要这么快吧）。
```go
ticker := time.NewTicker(e.ttl / 5)
```
建议改成这样
```go
ticker := time.NewTicker(e.ttl * time.Second / 5)
```

**Comment by liyue201** [comment]
已修复
