### ISSUE TITLE
etcd v3.3.18+ relay on grpc 1.26.0, how could install package using go mod tidy?

### ISSUE THREAD

**Issue by Yummy26** [liyue201/grpc-lb#18]
etcd: go.mod file

https://github.com/etcd-io/etcd/blob/master/go.mod

**Comment by Yummy26** [comment]
etcd using the package `google.golang.org/grpc/naming`, 

https://github.com/etcd-io/etcd/search?q=google.golang.org%2Fgrpc%2Fnaming

while the `naming module` only exist in the former version early than grpc@1.26.0.

**Comment by liyue201** [comment]
please use an older version of grpc-lb , which relies on grpc v1.26.0

```
require (
	github.com/coreos/etcd v3.3.18+incompatible
	github.com/liyue201/grpc-lb v0.0.0-20200901081538-e471cb60979d
	golang.org/x/net v0.0.0-20200707034311-ab3426394381
	google.golang.org/grpc v1.26.0
)

replace github.com/liyue201/grpc-lb => github.com/liyue201/grpc-lb v0.0.0-20200724072550-fcece951c1e2
```

**Comment by Yummy26** [comment]
Thx, That works.

As a complement, In case of solving the error  `undefined: grpc.ClientConnInterface `  for grpc v1.26.0,
we should using the protoc-gen-go as below, to build the *.pb.go && *.pb.gw.go .

`github.com/golang/protobuf/protoc-gen-go@v1.3.2`
