### ISSUE TITLE
close addrsChan?

### ISSUE THREAD

**Issue by qq1033731787** [liyue201/grpc-lb#8]
should close addrsChan when watcher close?

**Comment by liyue201** [comment]
yes，you are right

**Comment by qq1033731787** [comment]
请问有修复计划吗

------------------&nbsp;原始邮件&nbsp;------------------
发件人: "stirlingx"<notifications@github.com&gt;; 
发送时间: 2019年12月12日(星期四) 晚上8:18
收件人: "liyue201/grpc-lb"<grpc-lb@noreply.github.com&gt;; 
抄送: "rrrainy"<1033731787@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [liyue201/grpc-lb] close addrsChan? (#8)




yes，you are right

**Comment by liyue201** [comment]
有时间就修复
