### ISSUE TITLE
自定义负载均衡策略怎么实现

### ISSUE THREAD

**Issue by LeeGG** [liyue201/grpc-lb#9]
比如 proto 里有个account字段，我要根据服务个数取模调用对应的服务。
即： 我需要解析请求后根据请求字段确定请求转发的服务
请问这个需求怎么实现 ，在哪实现
🙆🙆🙆🙆🙆

**Comment by liyue201** [comment]
目前没有实现这个功能，不过你可以参考consistent_hash.go里面的逻辑写一个类似的包，将account通过context.Context传进去。在里面做负载均衡。
